name: focus_spot_finder
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android IInversioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.1
  country_list_pick: ^1.0.1+5
  cupertino_icons: ^1.0.2
  dio: ^4.0.3
  equatable: ^2.0.3
  favorite_button: ^0.0.4
  firebase_auth: ^3.3.11
  firebase_core: ^1.10.1
  firebase_dynamic_links: ^4.0.7
  firebase_storage: ^10.2.0
  firebase_crashlytics: ^2.6.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2
  flutter_image_compress: any
  flutter_rating_bar: ^4.0.0
  fluttertoast: ^8.0.8
  geocoder: ^0.2.1
  geolocator: ^8.0.0
  get: any
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.1.0
  hooks_riverpod: ^1.0.3
  http: ^0.13.4
  image_picker: any
  intl: ^0.17.0
  logger: ^1.1.0
  multiselect: ^0.0.4
  percent_indicator: ^3.4.0
  permission_handler: ^8.3.0
  share_plus: ^3.1.0
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.18
  visibility_detector: ^0.2.2
  bubble: ^1.2.1
  dialog_flowtter: ^0.3.1

dev_dependencies:
  flutter_app_name: ^0.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter_app_name:
  name: "Focus Spot Finder"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
